{{- if .Values.minio.enabled }}
apiVersion: v1
data:
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | b64enc | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword | b64enc | quote }}
kind: Secret
metadata:
  name: minio-secret
{{- end }}
