{{- if .Values.minio.enabled }}
apiVersion: v1
data:
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | b64enc | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword | b64enc | quote }}
  {{- if .Values.minio.console.enabled }}
  MINIO_BROWSER: {{ "on" | b64enc | quote }}
  MINIO_BROWSER_REDIRECT_URL: {{ .Values.minio.console.redirectUrl | b64enc | quote }}
  {{- else }}
  MINIO_BROWSER: {{ "off" | b64enc | quote }}
  {{- end }}
kind: Secret
metadata:
  name: minio-secret
{{- end }}
