{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "cbom-repository.labels" . | nindent 4 }}
  name: minio-service
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    - name: api
      port: {{ .Values.minio.service.apiPort }}
      protocol: "TCP"
    {{- if .Values.minio.console.enabled }}
    - name: console
      port: {{ .Values.minio.service.consolePort }}
      protocol: "TCP"
    {{- end }}
  selector:
    app.kubernetes.io/component: minio
    {{- include "cbom-repository.selectorLabels" . | nindent 4 }}
{{- end }}
