apiVersion: v1
data:
  access_key: {{ .Values.cbomRepo.accessKey | b64enc | quote }}
  secret_key: {{ .Values.cbomRepo.secretKey | b64enc | quote }}
kind: Secret
metadata:
  name: cbom-repository-secret
